[build]
  functions = "netlify/functions"

# Disable secrets scanning that's causing build failures
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/extract-url"
  to = "/.netlify/functions/extract-url"
  status = 200

[[redirects]]
  from = "/api/process-file"
  to = "/.netlify/functions/process-file"
  status = 200

[[redirects]]
  from = "/api/text-to-speech"
  to = "/.netlify/functions/text-to-speech"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
